// Code generated by sqlc. DO NOT EDIT.

package postgresql

import (
	"github.com/google/uuid"
)

type Urls struct {
	ID                     uuid.UUID
	HtmlVersion            string
	PageTitle              string
	HeadingsCount          string
	LinksCount             int32
	InaccessibleLinksCount int32
	HaveLoginForm          bool
}
